import { TransactionCategory } from '@/constants/types';
import {
  red,
  pink,
  teal,
  cyan,
  blue,
  grey,
  green,
  orange,
  purple,
  yellow,
  lightBlue,
  deepOrange,
  lightGreen,
} from '@mui/material/colors';

export const COLOR_MAP: Record<TransactionCategory, string> = {
  groceries: green[500],
  dining: orange[500],
  rent: deepOrange[500],
  utilities: cyan[500],
  home: lightBlue[400],
  auto: blue[500],
  transport: teal[500],
  shopping: purple[500],
  subscriptions: yellow[500],
  pets: pink[500],
  donations: red[500],
  education: lightGreen[500],
  sports: blue[700],
  entertainment: deepOrange[300],
  beauty: purple[300],
  healthcare: red[300],
  gifts: pink[300],
  savings: teal[300],
  others: grey[500],
  salary: green[700],
  investments: blue[800],
  ROI: cyan[700],
};
